"""Add status and due_date to Item.

Revision ID: 92f318a272de
Revises: a63c9427081b
Create Date: 2024-10-25 15:11:22.511023

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "92f318a272de"
down_revision = "a63c9427081b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "item",
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
    )
    op.add_column("item", sa.Column("due_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("item", "due_date")
    op.drop_column("item", "status")
    # ### end Alembic commands ###
